# coding: utf-8

"""
    fluid

    client for fluid  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Fluid
from Fluid.io.fluid-cloudnative.module.data_backup_status import DataBackupStatus  # noqa: E501
from Fluid.rest import ApiException


class TestDataBackupStatus(unittest.TestCase):
    """DataBackupStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataBackupStatus(self):
        """Test DataBackupStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Fluid.models.data_backup_status.DataBackupStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
