# coding: utf-8

"""
    fluid

    client for fluid  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import fluid
from fluid.models.affinity_strategy import AffinityStrategy  # noqa: E501
from fluid.rest import ApiException

class TestAffinityStrategy(unittest.TestCase):
    """AffinityStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AffinityStrategy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = fluid.models.affinity_strategy.AffinityStrategy()  # noqa: E501
        if include_optional :
            return AffinityStrategy(
                policy = '0', 
                prefers = [
                    fluid.models./prefer..Prefer(
                        name = '0', 
                        weight = 56, )
                    ], 
                requires = [
                    fluid.models./require..Require(
                        name = '0', )
                    ]
            )
        else :
            return AffinityStrategy(
        )

    def testAffinityStrategy(self):
        """Test AffinityStrategy"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
