# coding: utf-8

"""
    fluid

    client for fluid  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Fluid
from Fluid.io.fluid-cloudnative.module.cacheable_node_affinity import CacheableNodeAffinity  # noqa: E501
from Fluid.rest import ApiException


class TestCacheableNodeAffinity(unittest.TestCase):
    """CacheableNodeAffinity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCacheableNodeAffinity(self):
        """Test CacheableNodeAffinity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Fluid.models.cacheable_node_affinity.CacheableNodeAffinity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
