# coding: utf-8

"""
    fluid

    client for fluid  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Fluid
from Fluid.io.fluid-cloudnative.module.api_gateway_status import APIGatewayStatus  # noqa: E501
from Fluid.rest import ApiException


class TestAPIGatewayStatus(unittest.TestCase):
    """APIGatewayStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAPIGatewayStatus(self):
        """Test APIGatewayStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Fluid.models.api_gateway_status.APIGatewayStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
