# coding: utf-8

"""
    fluid

    client for fluid  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import fluid
from fluid.models.metadata_sync_policy import MetadataSyncPolicy  # noqa: E501
from fluid.rest import ApiException

class TestMetadataSyncPolicy(unittest.TestCase):
    """MetadataSyncPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MetadataSyncPolicy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = fluid.models.metadata_sync_policy.MetadataSyncPolicy()  # noqa: E501
        if include_optional :
            return MetadataSyncPolicy(
                auto_sync = True
            )
        else :
            return MetadataSyncPolicy(
        )

    def testMetadataSyncPolicy(self):
        """Test MetadataSyncPolicy"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
