# coding: utf-8

"""
    fluid

    client for fluid  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Fluid
from Fluid.io.fluid-cloudnative.module.alluxio_fuse_spec import AlluxioFuseSpec  # noqa: E501
from Fluid.rest import ApiException


class TestAlluxioFuseSpec(unittest.TestCase):
    """AlluxioFuseSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlluxioFuseSpec(self):
        """Test AlluxioFuseSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Fluid.models.alluxio_fuse_spec.AlluxioFuseSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
