# coding: utf-8

"""
    fluid

    client for fluid  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import fluid
from fluid.models.script_processor import ScriptProcessor  # noqa: E501
from fluid.rest import ApiException

class TestScriptProcessor(unittest.TestCase):
    """ScriptProcessor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ScriptProcessor
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = fluid.models.script_processor.ScriptProcessor()  # noqa: E501
        if include_optional :
            return ScriptProcessor(
                command = [
                    '0'
                    ], 
                env = [
                    None
                    ], 
                image = '0', 
                image_pull_policy = '0', 
                image_tag = '0', 
                resources = None, 
                restart_policy = '0', 
                source = '0', 
                volume_mounts = [
                    None
                    ], 
                volumes = [
                    None
                    ]
            )
        else :
            return ScriptProcessor(
                source = '0',
        )

    def testScriptProcessor(self):
        """Test ScriptProcessor"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
