# coding: utf-8

"""
    fluid

    client for fluid  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Fluid
from Fluid.io.fluid-cloudnative.module.jindo_runtime_spec import JindoRuntimeSpec  # noqa: E501
from Fluid.rest import ApiException


class TestJindoRuntimeSpec(unittest.TestCase):
    """JindoRuntimeSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJindoRuntimeSpec(self):
        """Test JindoRuntimeSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Fluid.models.jindo_runtime_spec.JindoRuntimeSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
