# -*- coding: utf-8 -*-


import pprint

import six
from fluid.configuration import Configuration


class JuiceFSRuntimeSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'disable_prometheus': 'bool',
        'fuse': 'JuiceFSFuseSpec',
        'init_users': 'InitUsersSpec',
        'job_worker': 'JuiceFSCompTemplateSpec',
        'juicefs_version': 'VersionSpec',
        'master': 'JuiceFSCompTemplateSpec',
        'replicas': 'int',
        'run_as': 'User',
        'tieredstore': 'TieredStore',
        'worker': 'JuiceFSCompTemplateSpec'
    }

    attribute_map = {
        'disable_prometheus': 'disablePrometheus',
        'fuse': 'fuse',
        'init_users': 'initUsers',
        'job_worker': 'jobWorker',
        'juicefs_version': 'juicefsVersion',
        'master': 'master',
        'replicas': 'replicas',
        'run_as': 'runAs',
        'tieredstore': 'tieredstore',
        'worker': 'worker'
    }

    def __init__(self, disable_prometheus=None, fuse=None, init_users=None, job_worker=None, juicefs_version=None, master=None, replicas=None, run_as=None, tieredstore=None, worker=None, _configuration=None):  # noqa: E501
        """JuiceFSRuntimeSpec - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._disable_prometheus = None
        self._fuse = None
        self._init_users = None
        self._job_worker = None
        self._juicefs_version = None
        self._master = None
        self._replicas = None
        self._run_as = None
        self._tieredstore = None
        self._worker = None
        self.discriminator = None

        if disable_prometheus is not None:
            self.disable_prometheus = disable_prometheus
        if fuse is not None:
            self.fuse = fuse
        if init_users is not None:
            self.init_users = init_users
        if job_worker is not None:
            self.job_worker = job_worker
        if juicefs_version is not None:
            self.juicefs_version = juicefs_version
        if master is not None:
            self.master = master
        if replicas is not None:
            self.replicas = replicas
        if run_as is not None:
            self.run_as = run_as
        if tieredstore is not None:
            self.tieredstore = tieredstore
        if worker is not None:
            self.worker = worker

    @property
    def disable_prometheus(self):
        """Gets the disable_prometheus of this JuiceFSRuntimeSpec.  # noqa: E501

        Disable monitoring for JuiceFS Runtime Prometheus is enabled by default  # noqa: E501

        :return: The disable_prometheus of this JuiceFSRuntimeSpec.  # noqa: E501
        :rtype: bool
        """
        return self._disable_prometheus

    @disable_prometheus.setter
    def disable_prometheus(self, disable_prometheus):
        """Sets the disable_prometheus of this JuiceFSRuntimeSpec.

        Disable monitoring for JuiceFS Runtime Prometheus is enabled by default  # noqa: E501

        :param disable_prometheus: The disable_prometheus of this JuiceFSRuntimeSpec.  # noqa: E501
        :type: bool
        """

        self._disable_prometheus = disable_prometheus

    @property
    def fuse(self):
        """Gets the fuse of this JuiceFSRuntimeSpec.  # noqa: E501

        Desired state for JuiceFS Fuse  # noqa: E501

        :return: The fuse of this JuiceFSRuntimeSpec.  # noqa: E501
        :rtype: JuiceFSFuseSpec
        """
        return self._fuse

    @fuse.setter
    def fuse(self, fuse):
        """Sets the fuse of this JuiceFSRuntimeSpec.

        Desired state for JuiceFS Fuse  # noqa: E501

        :param fuse: The fuse of this JuiceFSRuntimeSpec.  # noqa: E501
        :type: JuiceFSFuseSpec
        """

        self._fuse = fuse

    @property
    def init_users(self):
        """Gets the init_users of this JuiceFSRuntimeSpec.  # noqa: E501

        The spec of init users  # noqa: E501

        :return: The init_users of this JuiceFSRuntimeSpec.  # noqa: E501
        :rtype: InitUsersSpec
        """
        return self._init_users

    @init_users.setter
    def init_users(self, init_users):
        """Sets the init_users of this JuiceFSRuntimeSpec.

        The spec of init users  # noqa: E501

        :param init_users: The init_users of this JuiceFSRuntimeSpec.  # noqa: E501
        :type: InitUsersSpec
        """

        self._init_users = init_users

    @property
    def job_worker(self):
        """Gets the job_worker of this JuiceFSRuntimeSpec.  # noqa: E501

        The component spec of JuiceFS job Worker  # noqa: E501

        :return: The job_worker of this JuiceFSRuntimeSpec.  # noqa: E501
        :rtype: JuiceFSCompTemplateSpec
        """
        return self._job_worker

    @job_worker.setter
    def job_worker(self, job_worker):
        """Sets the job_worker of this JuiceFSRuntimeSpec.

        The component spec of JuiceFS job Worker  # noqa: E501

        :param job_worker: The job_worker of this JuiceFSRuntimeSpec.  # noqa: E501
        :type: JuiceFSCompTemplateSpec
        """

        self._job_worker = job_worker

    @property
    def juicefs_version(self):
        """Gets the juicefs_version of this JuiceFSRuntimeSpec.  # noqa: E501

        The version information that instructs fluid to orchestrate a particular version of JuiceFS.  # noqa: E501

        :return: The juicefs_version of this JuiceFSRuntimeSpec.  # noqa: E501
        :rtype: VersionSpec
        """
        return self._juicefs_version

    @juicefs_version.setter
    def juicefs_version(self, juicefs_version):
        """Sets the juicefs_version of this JuiceFSRuntimeSpec.

        The version information that instructs fluid to orchestrate a particular version of JuiceFS.  # noqa: E501

        :param juicefs_version: The juicefs_version of this JuiceFSRuntimeSpec.  # noqa: E501
        :type: VersionSpec
        """

        self._juicefs_version = juicefs_version

    @property
    def master(self):
        """Gets the master of this JuiceFSRuntimeSpec.  # noqa: E501

        The component spec of JuiceFS master  # noqa: E501

        :return: The master of this JuiceFSRuntimeSpec.  # noqa: E501
        :rtype: JuiceFSCompTemplateSpec
        """
        return self._master

    @master.setter
    def master(self, master):
        """Sets the master of this JuiceFSRuntimeSpec.

        The component spec of JuiceFS master  # noqa: E501

        :param master: The master of this JuiceFSRuntimeSpec.  # noqa: E501
        :type: JuiceFSCompTemplateSpec
        """

        self._master = master

    @property
    def replicas(self):
        """Gets the replicas of this JuiceFSRuntimeSpec.  # noqa: E501

        The replicas of the worker, need to be specified  # noqa: E501

        :return: The replicas of this JuiceFSRuntimeSpec.  # noqa: E501
        :rtype: int
        """
        return self._replicas

    @replicas.setter
    def replicas(self, replicas):
        """Sets the replicas of this JuiceFSRuntimeSpec.

        The replicas of the worker, need to be specified  # noqa: E501

        :param replicas: The replicas of this JuiceFSRuntimeSpec.  # noqa: E501
        :type: int
        """

        self._replicas = replicas

    @property
    def run_as(self):
        """Gets the run_as of this JuiceFSRuntimeSpec.  # noqa: E501

        Manage the user to run Juicefs Runtime  # noqa: E501

        :return: The run_as of this JuiceFSRuntimeSpec.  # noqa: E501
        :rtype: User
        """
        return self._run_as

    @run_as.setter
    def run_as(self, run_as):
        """Sets the run_as of this JuiceFSRuntimeSpec.

        Manage the user to run Juicefs Runtime  # noqa: E501

        :param run_as: The run_as of this JuiceFSRuntimeSpec.  # noqa: E501
        :type: User
        """

        self._run_as = run_as

    @property
    def tieredstore(self):
        """Gets the tieredstore of this JuiceFSRuntimeSpec.  # noqa: E501

        Tiered storage used by JuiceFS  # noqa: E501

        :return: The tieredstore of this JuiceFSRuntimeSpec.  # noqa: E501
        :rtype: TieredStore
        """
        return self._tieredstore

    @tieredstore.setter
    def tieredstore(self, tieredstore):
        """Sets the tieredstore of this JuiceFSRuntimeSpec.

        Tiered storage used by JuiceFS  # noqa: E501

        :param tieredstore: The tieredstore of this JuiceFSRuntimeSpec.  # noqa: E501
        :type: TieredStore
        """

        self._tieredstore = tieredstore

    @property
    def worker(self):
        """Gets the worker of this JuiceFSRuntimeSpec.  # noqa: E501

        The component spec of JuiceFS worker  # noqa: E501

        :return: The worker of this JuiceFSRuntimeSpec.  # noqa: E501
        :rtype: JuiceFSCompTemplateSpec
        """
        return self._worker

    @worker.setter
    def worker(self, worker):
        """Sets the worker of this JuiceFSRuntimeSpec.

        The component spec of JuiceFS worker  # noqa: E501

        :param worker: The worker of this JuiceFSRuntimeSpec.  # noqa: E501
        :type: JuiceFSCompTemplateSpec
        """

        self._worker = worker

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JuiceFSRuntimeSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JuiceFSRuntimeSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, JuiceFSRuntimeSpec):
            return True

        return self.to_dict() != other.to_dict()
