# coding: utf-8

"""
    fluid

    client for fluid  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fluid.configuration import Configuration


class DataToMigrate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'dataset': 'DatasetToMigrate',
        'external_storage': 'ExternalStorage'
    }

    attribute_map = {
        'dataset': 'dataset',
        'external_storage': 'externalStorage'
    }

    def __init__(self, dataset=None, external_storage=None, local_vars_configuration=None):  # noqa: E501
        """DataToMigrate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._dataset = None
        self._external_storage = None
        self.discriminator = None

        if dataset is not None:
            self.dataset = dataset
        if external_storage is not None:
            self.external_storage = external_storage

    @property
    def dataset(self):
        """Gets the dataset of this DataToMigrate.  # noqa: E501


        :return: The dataset of this DataToMigrate.  # noqa: E501
        :rtype: DatasetToMigrate
        """
        return self._dataset

    @dataset.setter
    def dataset(self, dataset):
        """Sets the dataset of this DataToMigrate.


        :param dataset: The dataset of this DataToMigrate.  # noqa: E501
        :type: DatasetToMigrate
        """

        self._dataset = dataset

    @property
    def external_storage(self):
        """Gets the external_storage of this DataToMigrate.  # noqa: E501


        :return: The external_storage of this DataToMigrate.  # noqa: E501
        :rtype: ExternalStorage
        """
        return self._external_storage

    @external_storage.setter
    def external_storage(self, external_storage):
        """Sets the external_storage of this DataToMigrate.


        :param external_storage: The external_storage of this DataToMigrate.  # noqa: E501
        :type: ExternalStorage
        """

        self._external_storage = external_storage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataToMigrate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DataToMigrate):
            return True

        return self.to_dict() != other.to_dict()
