# coding: utf-8

"""
    fluid

    client for fluid  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fluid.configuration import Configuration


class WaitingStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'operation_complete': 'bool'
    }

    attribute_map = {
        'operation_complete': 'operationComplete'
    }

    def __init__(self, operation_complete=None, local_vars_configuration=None):  # noqa: E501
        """WaitingStatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._operation_complete = None
        self.discriminator = None

        if operation_complete is not None:
            self.operation_complete = operation_complete

    @property
    def operation_complete(self):
        """Gets the operation_complete of this WaitingStatus.  # noqa: E501

        OperationComplete indicates if the preceding operation is complete  # noqa: E501

        :return: The operation_complete of this WaitingStatus.  # noqa: E501
        :rtype: bool
        """
        return self._operation_complete

    @operation_complete.setter
    def operation_complete(self, operation_complete):
        """Sets the operation_complete of this WaitingStatus.

        OperationComplete indicates if the preceding operation is complete  # noqa: E501

        :param operation_complete: The operation_complete of this WaitingStatus.  # noqa: E501
        :type: bool
        """

        self._operation_complete = operation_complete

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WaitingStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WaitingStatus):
            return True

        return self.to_dict() != other.to_dict()
